# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

WbAccessToken.create([
  { :wb_user_id => 1, :value => "2.002jeAYB6AEbCC02546cd40b0t81TG", :expires_at => 1537170639, :created_at => "2013-09-18 07:50:42", :updated_at => "2013-09-18 11:04:18", :success_count => 3, :error_count => 0 },
  { :wb_user_id => 2, :value => "2.00PFDZ3D6AEbCCf92013f263I2hRXE", :expires_at => 1379617199, :created_at => "2013-09-18 07:59:59", :updated_at => "2013-09-18 11:04:20", :success_count => 6, :error_count => 0 }
], :without_protection => true )



WbStatus.create([
  { :wb_target_user_id => nil, :wb_id => nil, :wb_mid => nil, :wb_idstr => nil, :posted_at => nil, :message => "", :attitudes_count => nil, :comments_count => nil, :reposts_count => nil, :thumbnail_pic => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



WbStatusFrame.create([
  { :wb_status_id => nil, :attitudes_count => nil, :comments_count => nil, :reposts_count => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



WbTargetUser.create([
  { :wb_id => 1197161814, :name => "李开复", :link => "kaifulee", :description => "创新工场CEO，媒体联系：press@chuangxin.com", :profile_img_link => "http://tp3.sinaimg.cn/1197161814/180/1290146312/1", :followers_count => 51669062, :friends_count => 551, :statuses_count => 13637, :favourites_count => 882, :verified => true, :verified_reason => "创新工场董事长兼首席执行官", :lang => "zh-cn", :created_at => "2013-09-16 09:18:02", :updated_at => "2013-09-18 11:04:16", :domain => "kaifulee" },
  { :wb_id => 3235021073, :name => "最美和声", :link => "zuimeihesheng", :description => "2013年7月20日起，每周六晚在北京卫视，导师范玮琪、萧敬腾、陈羽凡、胡海泉，主持杨坤齐聚《最美和声》，还陆续有您意想不到的助场嘉宾，...", :profile_img_link => "http://tp2.sinaimg.cn/3235021073/180/5668427421/0", :followers_count => 550547, :friends_count => 360, :statuses_count => 1498, :favourites_count => 0, :verified => true, :verified_reason => "《最美和声》栏目", :lang => "zh-cn", :created_at => "2013-09-18 08:22:30", :updated_at => "2013-09-18 11:04:17", :domain => "zuimeihesheng" },
  { :wb_id => 2803301701, :name => "人民日报", :link => "rmrb", :description => "参与 沟通 记录时代", :profile_img_link => "http://tp2.sinaimg.cn/2803301701/180/40021767685/1", :followers_count => 10237024, :friends_count => 219, :statuses_count => 16350, :favourites_count => 14, :verified => true, :verified_reason => "《人民日报》法人微博", :lang => "zh-cn", :created_at => "2013-09-18 08:23:11", :updated_at => "2013-09-18 11:04:18", :domain => "rmrb" },
  { :wb_id => 3708524475, :name => "济南中院", :link => "jinanzhongyuan", :description => "山东省济南市中级人民法院官方微博", :profile_img_link => "http://tp4.sinaimg.cn/3708524475/180/5671775169/1", :followers_count => 535546, :friends_count => 20, :statuses_count => 195, :favourites_count => 2, :verified => true, :verified_reason => "山东省济南市中级人民法院官方微博", :lang => "zh-cn", :created_at => "2013-09-18 08:34:21", :updated_at => "2013-09-18 11:04:20", :domain => "jinanzhongyuan" }
], :without_protection => true )



WbTargetUserFrame.create([
  { :wb_target_user_id => 1, :followers_count => 51660391, :statuses_count => 13626, :favourites_count => nil, :followers_per_hour => nil, :followers_per_hour_smoothed => nil, :created_at => "2013-09-16 09:19:14", :updated_at => "2013-09-16 09:19:14" },
  { :wb_target_user_id => 1, :followers_count => 51668480, :statuses_count => 13636, :favourites_count => nil, :followers_per_hour => 171.587, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 08:27:46", :updated_at => "2013-09-18 09:26:46" },
  { :wb_target_user_id => 2, :followers_count => 550554, :statuses_count => 1497, :favourites_count => nil, :followers_per_hour => nil, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 08:27:52", :updated_at => "2013-09-18 08:27:52" },
  { :wb_target_user_id => 3, :followers_count => 10232886, :statuses_count => 16342, :favourites_count => nil, :followers_per_hour => nil, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 08:27:56", :updated_at => "2013-09-18 08:27:56" },
  { :wb_target_user_id => 1, :followers_count => 51668817, :statuses_count => 13637, :favourites_count => nil, :followers_per_hour => 331.566, :followers_per_hour_smoothed => 171.587, :created_at => "2013-09-18 09:28:45", :updated_at => "2013-09-18 09:29:14" },
  { :wb_target_user_id => 2, :followers_count => 550555, :statuses_count => 1498, :favourites_count => nil, :followers_per_hour => 0.984952, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 09:28:47", :updated_at => "2013-09-18 09:29:14" },
  { :wb_target_user_id => 3, :followers_count => 10234570, :statuses_count => 16346, :favourites_count => nil, :followers_per_hour => 1660.02, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 09:28:48", :updated_at => "2013-09-18 09:29:14" },
  { :wb_target_user_id => 4, :followers_count => 535291, :statuses_count => 195, :favourites_count => nil, :followers_per_hour => nil, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 09:28:49", :updated_at => "2013-09-18 09:28:49" },
  { :wb_target_user_id => 1, :followers_count => 51669062, :statuses_count => 13637, :favourites_count => nil, :followers_per_hour => 153.9, :followers_per_hour_smoothed => 187.585, :created_at => "2013-09-18 11:04:16", :updated_at => "2013-09-18 11:04:25" },
  { :wb_target_user_id => 2, :followers_count => 550547, :statuses_count => 1498, :favourites_count => nil, :followers_per_hour => -5.02618, :followers_per_hour_smoothed => 0.984952, :created_at => "2013-09-18 11:04:17", :updated_at => "2013-09-18 11:04:25" },
  { :wb_target_user_id => 3, :followers_count => 10237024, :statuses_count => 16350, :favourites_count => nil, :followers_per_hour => 1541.78, :followers_per_hour_smoothed => 1660.02, :created_at => "2013-09-18 11:04:18", :updated_at => "2013-09-18 11:04:25" },
  { :wb_target_user_id => 4, :followers_count => 535546, :statuses_count => 195, :favourites_count => nil, :followers_per_hour => 160.181, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 11:04:20", :updated_at => "2013-09-18 11:04:25" }
], :without_protection => true )



WbUser.create([
  { :wb_id => 1418684827, :name => "CaRro_T", :created_at => "2013-09-16 09:11:01", :updated_at => "2013-09-16 09:11:01" },
  { :wb_id => 3081831225, :name => "detanmao", :created_at => "2013-09-18 07:59:53", :updated_at => "2013-09-18 07:59:53" }
], :without_protection => true )


