# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

# WbAccessToken.create([
#   { :wb_user_id => 1, :value => "2.002jeAYBove4BE06f3626588Q25RDD", :expires_at => 1537215026, :created_at => "2013-09-18 20:10:27", :updated_at => "2013-09-20 13:10:19", :success_count => 41, :error_count => 0 },
#   { :wb_user_id => 2, :value => "2.009u3wHD6AEbCC2ba8447ea3s5DHIE", :expires_at => 1379703599, :created_at => "2013-09-19 08:07:21", :updated_at => "2013-09-20 13:10:22", :success_count => 21, :error_count => 0 }
# ], :without_protection => true )



WbStatus.create([
  { :wb_target_user_id => 1, :wb_id => "3624262936142116", :wb_mid => "3624262936142116", :wb_idstr => "3624262936142116", :posted_at => "2013-09-19 07:18:02", :message => "癌症是慢性病，抗癌需要多方面的长期抗争。我现在西医化疗 + 运动 + 睡眠 + 饮食多方面同时努力。感谢 @台湾陈月卿 的四种果汁食谱，每天喝1-2杯，辅助营养，增加免疫力，大家可以参考。果汁大王 @潘石屹 也请参考：听说除了防癌养生，还可以治愈结巴哦！[偷笑]", :attitudes_count => 2323, :comments_count => 2636, :reposts_count => 3159, :created_at => "2013-09-19 07:30:31", :updated_at => "2013-09-20 13:10:06", :sentiment => 0.042623583016166505 },
  { :wb_target_user_id => 2, :wb_id => "3624251145421477", :wb_mid => "3624251145421477", :wb_idstr => "3624251145421477", :posted_at => "2013-09-19 06:31:10", :message => "#中秋快乐#2013 BTV中秋特别节目将于今晚19点35分在BTV文艺频道现场直播，并于22时20分在北京卫视重播。 超女@周笔畅、 好声音@平安anson 、梦之声@央吉玛 等人气歌手将同台飙歌，大病初愈的“年画娃娃”@邓鸣贺 在出院后首度登台。荧屏红人和民间达人汇聚一堂，共同打造一场别具风格的中秋特别节目。", :attitudes_count => 6, :comments_count => 2, :reposts_count => 2, :created_at => "2013-09-19 07:30:33", :updated_at => "2013-09-20 13:10:08", :sentiment => 0.08965602201629828 },
  { :wb_target_user_id => 3, :wb_id => "3624263447954923", :wb_mid => "3624263447954923", :wb_idstr => "3624263447954923", :posted_at => "2013-09-19 07:20:04", :message => "甄嬛刚刚入宫时还是一个简单纯朴的女孩，但在残酷的宫廷环境中，时刻受到以皇后为首的宫廷势力的暗算和迫害。之后，她终于懂得了一个“真理”：你必须学会比对手更加阴险毒辣，才能立于不败之地。也就是说，你必须更坏才能战胜对手。这就是《甄嬛传》传播和宣扬的价值观。[思考]", :attitudes_count => 312, :comments_count => 1933, :reposts_count => 3463, :created_at => "2013-09-19 07:30:35", :updated_at => "2013-09-20 13:10:09", :sentiment => -0.0257266712679753 },
  { :wb_target_user_id => 4, :wb_id => "3624178043793493", :wb_mid => "3624178043793493", :wb_idstr => "3624178043793493", :posted_at => "2013-09-19 01:40:41", :message => "【中秋祝福】海上生明月，天涯共此时。值中秋佳节来临之际，济南中院向关心支持我院工作的社会各界人士和广大网友致以衷心的感谢和节日的祝福！祝大家中秋快乐，阖家幸福！", :attitudes_count => 181, :comments_count => 169, :reposts_count => 1070, :created_at => "2013-09-19 07:30:36", :updated_at => "2013-09-20 13:10:10", :sentiment => 1.0 },
  { :wb_target_user_id => 5, :wb_id => "3553008904456427", :wb_mid => "3553008904456427", :wb_idstr => "3553008904456427", :posted_at => "2013-03-06 16:19:58", :message => "#Adobe数字营销峰会2013# 经过2天的客户咨询会议和培训，2013 Adobe Digital Marketing Summit正式开幕了，CEO Shantanu和数字营销高级副总裁Brad在开幕式上致辞。有超过5000人的客户和合作伙伴将参加2天的峰会和产品分会交流活动。  #拼图#", :attitudes_count => 3, :comments_count => 16, :reposts_count => 6, :created_at => "2013-09-19 07:30:38", :updated_at => "2013-09-20 13:10:11", :sentiment => 0.21687678237107091 },
  { :wb_target_user_id => 3, :wb_id => "3624271312222895", :wb_mid => "3624271312222895", :wb_idstr => "3624271312222895", :posted_at => "2013-09-19 07:51:18", :message => "【这12个中国地名，你能读对几个？[思考]】1.浙江丽(lí)水；2.安徽亳(bó)州；3.上海莘(xīn)庄；4.浙江台(tāi)州；5.河南浚(xùn)县；6.江西铅(yán)山；7.新疆巴音郭楞(léng)；8.内蒙古巴彦淖(nào)尔；9.河北蔚(yù)县；10.安徽六(lù)安；11.湖南耒(lěi)阳；12.重庆涪(fú)陵。", :attitudes_count => 752, :comments_count => 1469, :reposts_count => 11153, :created_at => "2013-09-19 07:51:57", :updated_at => "2013-09-20 13:10:13", :sentiment => 0.008430584348729677 },
  { :wb_target_user_id => 1, :wb_id => "3624358071476529", :wb_mid => "3624358071476529", :wb_idstr => "3624358071476529", :posted_at => "2013-09-19 13:36:04", :message => "【不要成为\"紧急\"的奴隶】人的核心竟争力有时超过一半是来自重要而不紧急的事情：1）读书，特别读哪些非实用性的书；2）锻炼身体3、与智者交朋友；3）听音乐会看电影戏剧等艺术活动；4）潜心一到两项业余爱好6、广交朋友并为他们做事情。这些看起来都不是最最紧急的活动，但是它们打造了你的生活品质。", :attitudes_count => 6268, :comments_count => 4414, :reposts_count => 28612, :created_at => "2013-09-19 18:58:56", :updated_at => "2013-09-20 13:10:14", :sentiment => -0.04804143583599954 },
  { :wb_target_user_id => 2, :wb_id => "3624358368594227", :wb_mid => "3624358368594227", :wb_idstr => "3624358368594227", :posted_at => "2013-09-19 13:37:13", :message => "#中秋快乐#【今夜属于你】“在这个温馨的夜，我需要你，我属于你。夜，有你而美丽”，无论你身在何处，我们都抬头仰望同一轮明月。这一刻，情暖中秋夜，月圆梦更圆。伴随着这首《今夜属于你》，BTV中秋特别节目圆满结束了。感谢您的收看！今晚22:20北京卫视将为您重播，敬请关注。再次祝您中秋快乐！", :attitudes_count => 11, :comments_count => 2, :reposts_count => 2, :created_at => "2013-09-19 18:58:58", :updated_at => "2013-09-20 13:10:15", :sentiment => 0.09164541103795554 },
  { :wb_target_user_id => 3, :wb_id => "3624386571682998", :wb_mid => "3624386571682998", :wb_idstr => "3624386571682998", :posted_at => "2013-09-19 15:29:20", :message => "【你好，明天】月无私照，同浴灵辉；人各天涯，情共此时。今夜，朗月清风送最美祝福：一切圆满，今日，每日。安。", :attitudes_count => 596, :comments_count => 350, :reposts_count => 2105, :created_at => "2013-09-19 18:58:59", :updated_at => "2013-09-20 13:10:16", :sentiment => 0.05633163178469374 },
  { :wb_target_user_id => 1, :wb_id => "3624605728298346", :wb_mid => "3624605728298346", :wb_idstr => "3624605728298346", :posted_at => "2013-09-20 06:00:10", :message => "真正的越狱大师！[哈哈]", :attitudes_count => 4287, :comments_count => 2549, :reposts_count => 13273, :created_at => "2013-09-20 13:09:13", :updated_at => "2013-09-20 13:14:07", :sentiment => 0.2595745030915525 },
  { :wb_target_user_id => 2, :wb_id => "3624636200229528", :wb_mid => "3624636200229528", :wb_idstr => "3624636200229528", :posted_at => "2013-09-20 08:01:15", :message => "#最美和声#快乐的假期一波接一波，国庆也还得这么度过呦！[偷笑]", :attitudes_count => 3, :comments_count => 1, :reposts_count => 1, :created_at => "2013-09-20 13:09:14", :updated_at => "2013-09-20 13:14:10", :sentiment => 0.631811583342372 },
  { :wb_target_user_id => 3, :wb_id => "3624708966925528", :wb_mid => "3624708966925528", :wb_idstr => "3624708966925528", :posted_at => "2013-09-20 12:50:20", :message => "【老元：儿子结婚，卖光了羊，花光存款，还欠了5万】甘肃会宁县北部山区的老元说，“原来养着十几只羊。去年儿子结婚，光彩礼就5万，加上买家具、办酒席，总共花了八九万。卖掉十几只羊，花光不多的存款，还拉了5万元的账”。一些基层干部说，越穷的地方，彩礼越是“应声涨价”。", :attitudes_count => 36, :comments_count => 196, :reposts_count => 243, :created_at => "2013-09-20 13:09:15", :updated_at => "2013-09-20 13:14:14", :sentiment => 0.033412389440921286 },
  { :wb_target_user_id => 4, :wb_id => "3624533519132676", :wb_mid => "3624533519132676", :wb_idstr => "3624533519132676", :posted_at => "2013-09-20 01:13:14", :message => "【法律格言】官不私亲，法不遗爱，上下无事，唯法所在。——《慎子·君臣》", :attitudes_count => 124, :comments_count => 102, :reposts_count => 797, :created_at => "2013-09-20 13:09:16", :updated_at => "2013-09-20 13:14:17", :sentiment => -0.5232582685778219 }
], :without_protection => true )



WbStatusFrame.create([
  { :wb_status_id => 1, :attitudes_count => 431, :comments_count => 650, :reposts_count => 638, :created_at => "2013-09-19 07:46:34", :updated_at => "2013-09-19 07:46:34" },
  { :wb_status_id => 2, :attitudes_count => 4, :comments_count => 1, :reposts_count => 1, :created_at => "2013-09-19 07:46:35", :updated_at => "2013-09-19 07:46:35" },
  { :wb_status_id => 3, :attitudes_count => 73, :comments_count => 581, :reposts_count => 617, :created_at => "2013-09-19 07:46:36", :updated_at => "2013-09-19 07:46:36" },
  { :wb_status_id => 4, :attitudes_count => 129, :comments_count => 249, :reposts_count => 561, :created_at => "2013-09-19 07:46:38", :updated_at => "2013-09-19 07:46:38" },
  { :wb_status_id => 5, :attitudes_count => 3, :comments_count => 16, :reposts_count => 6, :created_at => "2013-09-19 07:46:39", :updated_at => "2013-09-19 07:46:39" },
  { :wb_status_id => 1, :attitudes_count => 495, :comments_count => 718, :reposts_count => 751, :created_at => "2013-09-19 07:52:46", :updated_at => "2013-09-19 07:52:46" },
  { :wb_status_id => 2, :attitudes_count => 4, :comments_count => 1, :reposts_count => 1, :created_at => "2013-09-19 07:52:47", :updated_at => "2013-09-19 07:52:47" },
  { :wb_status_id => 3, :attitudes_count => 89, :comments_count => 671, :reposts_count => 709, :created_at => "2013-09-19 07:52:48", :updated_at => "2013-09-19 07:52:48" },
  { :wb_status_id => 4, :attitudes_count => 130, :comments_count => 249, :reposts_count => 561, :created_at => "2013-09-19 07:52:52", :updated_at => "2013-09-19 07:52:52" },
  { :wb_status_id => 5, :attitudes_count => 3, :comments_count => 16, :reposts_count => 6, :created_at => "2013-09-19 07:52:53", :updated_at => "2013-09-19 07:52:53" },
  { :wb_status_id => 6, :attitudes_count => 16, :comments_count => 22, :reposts_count => 83, :created_at => "2013-09-19 07:52:55", :updated_at => "2013-09-19 07:52:55" },
  { :wb_status_id => 1, :attitudes_count => 2115, :comments_count => 2396, :reposts_count => 2783, :created_at => "2013-09-19 19:00:19", :updated_at => "2013-09-19 19:00:19" },
  { :wb_status_id => 2, :attitudes_count => 5, :comments_count => 2, :reposts_count => 2, :created_at => "2013-09-19 19:00:21", :updated_at => "2013-09-19 19:00:21" },
  { :wb_status_id => 3, :attitudes_count => 297, :comments_count => 1851, :reposts_count => 3176, :created_at => "2013-09-19 19:00:22", :updated_at => "2013-09-19 19:00:22" },
  { :wb_status_id => 4, :attitudes_count => 165, :comments_count => 172, :reposts_count => 888, :created_at => "2013-09-19 19:00:24", :updated_at => "2013-09-19 19:00:24" },
  { :wb_status_id => 5, :attitudes_count => 3, :comments_count => 16, :reposts_count => 6, :created_at => "2013-09-19 19:00:25", :updated_at => "2013-09-19 19:00:25" },
  { :wb_status_id => 6, :attitudes_count => 357, :comments_count => 805, :reposts_count => 6849, :created_at => "2013-09-19 19:00:27", :updated_at => "2013-09-19 19:00:27" },
  { :wb_status_id => 7, :attitudes_count => 3027, :comments_count => 1932, :reposts_count => 12703, :created_at => "2013-09-19 19:00:28", :updated_at => "2013-09-19 19:00:28" },
  { :wb_status_id => 8, :attitudes_count => 7, :comments_count => 2, :reposts_count => 2, :created_at => "2013-09-19 19:00:30", :updated_at => "2013-09-19 19:00:30" },
  { :wb_status_id => 9, :attitudes_count => 415, :comments_count => 295, :reposts_count => 1728, :created_at => "2013-09-19 19:00:32", :updated_at => "2013-09-19 19:00:32" },
  { :wb_status_id => 1, :attitudes_count => 2120, :comments_count => 2399, :reposts_count => 2787, :created_at => "2013-09-19 19:57:29", :updated_at => "2013-09-19 19:57:29" },
  { :wb_status_id => 2, :attitudes_count => 5, :comments_count => 2, :reposts_count => 2, :created_at => "2013-09-19 19:57:30", :updated_at => "2013-09-19 19:57:30" },
  { :wb_status_id => 3, :attitudes_count => 297, :comments_count => 1852, :reposts_count => 3177, :created_at => "2013-09-19 19:57:31", :updated_at => "2013-09-19 19:57:31" },
  { :wb_status_id => 4, :attitudes_count => 165, :comments_count => 172, :reposts_count => 888, :created_at => "2013-09-19 19:57:32", :updated_at => "2013-09-19 19:57:32" },
  { :wb_status_id => 5, :attitudes_count => 3, :comments_count => 16, :reposts_count => 6, :created_at => "2013-09-19 19:57:33", :updated_at => "2013-09-19 19:57:33" },
  { :wb_status_id => 6, :attitudes_count => 357, :comments_count => 807, :reposts_count => 6874, :created_at => "2013-09-19 19:57:34", :updated_at => "2013-09-19 19:57:34" },
  { :wb_status_id => 7, :attitudes_count => 3072, :comments_count => 1960, :reposts_count => 12959, :created_at => "2013-09-19 19:57:35", :updated_at => "2013-09-19 19:57:35" },
  { :wb_status_id => 8, :attitudes_count => 7, :comments_count => 2, :reposts_count => 2, :created_at => "2013-09-19 19:57:36", :updated_at => "2013-09-19 19:57:36" },
  { :wb_status_id => 9, :attitudes_count => 419, :comments_count => 298, :reposts_count => 1739, :created_at => "2013-09-19 19:57:38", :updated_at => "2013-09-19 19:57:38" },
  { :wb_status_id => 1, :attitudes_count => 2323, :comments_count => 2636, :reposts_count => 3159, :created_at => "2013-09-20 13:10:06", :updated_at => "2013-09-20 13:10:06" },
  { :wb_status_id => 2, :attitudes_count => 6, :comments_count => 2, :reposts_count => 2, :created_at => "2013-09-20 13:10:08", :updated_at => "2013-09-20 13:10:08" },
  { :wb_status_id => 3, :attitudes_count => 312, :comments_count => 1933, :reposts_count => 3463, :created_at => "2013-09-20 13:10:09", :updated_at => "2013-09-20 13:10:09" },
  { :wb_status_id => 4, :attitudes_count => 181, :comments_count => 169, :reposts_count => 1070, :created_at => "2013-09-20 13:10:10", :updated_at => "2013-09-20 13:10:10" },
  { :wb_status_id => 5, :attitudes_count => 3, :comments_count => 16, :reposts_count => 6, :created_at => "2013-09-20 13:10:11", :updated_at => "2013-09-20 13:10:11" },
  { :wb_status_id => 6, :attitudes_count => 752, :comments_count => 1469, :reposts_count => 11153, :created_at => "2013-09-20 13:10:13", :updated_at => "2013-09-20 13:10:13" },
  { :wb_status_id => 7, :attitudes_count => 6268, :comments_count => 4414, :reposts_count => 28612, :created_at => "2013-09-20 13:10:14", :updated_at => "2013-09-20 13:10:14" },
  { :wb_status_id => 8, :attitudes_count => 11, :comments_count => 2, :reposts_count => 2, :created_at => "2013-09-20 13:10:15", :updated_at => "2013-09-20 13:10:15" },
  { :wb_status_id => 9, :attitudes_count => 596, :comments_count => 350, :reposts_count => 2105, :created_at => "2013-09-20 13:10:16", :updated_at => "2013-09-20 13:10:16" },
  { :wb_status_id => 10, :attitudes_count => 4287, :comments_count => 2549, :reposts_count => 13273, :created_at => "2013-09-20 13:10:17", :updated_at => "2013-09-20 13:10:17" },
  { :wb_status_id => 11, :attitudes_count => 3, :comments_count => 1, :reposts_count => 1, :created_at => "2013-09-20 13:10:19", :updated_at => "2013-09-20 13:10:19" },
  { :wb_status_id => 12, :attitudes_count => 36, :comments_count => 196, :reposts_count => 243, :created_at => "2013-09-20 13:10:20", :updated_at => "2013-09-20 13:10:20" },
  { :wb_status_id => 13, :attitudes_count => 124, :comments_count => 102, :reposts_count => 797, :created_at => "2013-09-20 13:10:22", :updated_at => "2013-09-20 13:10:22" }
], :without_protection => true )



WbTargetUser.create([
  { :wb_id => 1197161814, :name => "李开复", :link => "kaifulee", :description => "创新工场CEO，媒体联系：press@chuangxin.com", :profile_img_link => "http://tp3.sinaimg.cn/1197161814/180/1290146312/1", :followers_count => 51686529, :friends_count => 551, :statuses_count => 13644, :favourites_count => 882, :verified => true, :verified_reason => "创新工场董事长兼首席执行官", :lang => "zh-cn", :created_at => "2013-09-16 09:18:02", :updated_at => "2013-09-20 13:09:13", :domain => "kaifulee" },
  { :wb_id => 3235021073, :name => "最美和声", :link => "zuimeihesheng", :description => "2013年7月20日起，每周六晚在北京卫视，导师范玮琪、萧敬腾、陈羽凡、胡海泉，主持杨坤齐聚《最美和声》，还陆续有您意想不到的助场嘉宾，...", :profile_img_link => "http://tp2.sinaimg.cn/3235021073/180/5668427421/0", :followers_count => 550588, :friends_count => 360, :statuses_count => 1509, :favourites_count => 0, :verified => true, :verified_reason => "《最美和声》栏目", :lang => "zh-cn", :created_at => "2013-09-18 08:22:30", :updated_at => "2013-09-20 13:09:14", :domain => "zuimeihesheng" },
  { :wb_id => 2803301701, :name => "人民日报", :link => "rmrb", :description => "参与 沟通 记录时代", :profile_img_link => "http://tp2.sinaimg.cn/2803301701/180/40021767685/1", :followers_count => 10297474, :friends_count => 220, :statuses_count => 16431, :favourites_count => 14, :verified => true, :verified_reason => "《人民日报》法人微博", :lang => "zh-cn", :created_at => "2013-09-18 08:23:11", :updated_at => "2013-09-20 13:09:15", :domain => "rmrb" },
  { :wb_id => 3708524475, :name => "济南中院", :link => "jinanzhongyuan", :description => "山东省济南市中级人民法院官方微博", :profile_img_link => "http://tp4.sinaimg.cn/3708524475/180/5671775169/1", :followers_count => 536047, :friends_count => 20, :statuses_count => 197, :favourites_count => 2, :verified => true, :verified_reason => "山东省济南市中级人民法院官方微博", :lang => "zh-cn", :created_at => "2013-09-18 08:34:21", :updated_at => "2013-09-20 13:09:16", :domain => "jinanzhongyuan" },
  { :wb_id => 2865743940, :name => "数字营销社区网", :link => "digitalmarketingcom", :description => "数字营销社区网站 www.fenxi8.cn 官方微博", :profile_img_link => "http://tp1.sinaimg.cn/2865743940/180/40005771504/1", :followers_count => 2340, :friends_count => 1232, :statuses_count => 655, :favourites_count => 0, :verified => false, :verified_reason => "", :lang => "zh-cn", :created_at => "2013-09-18 19:21:23", :updated_at => "2013-09-20 13:09:18", :domain => "digitalmarketingcom" }
], :without_protection => true )



WbTargetUserFrame.create([
  { :wb_target_user_id => 1, :followers_count => 51660391, :statuses_count => 13626, :favourites_count => nil, :followers_per_hour => nil, :followers_per_hour_smoothed => nil, :created_at => "2013-09-16 09:19:14", :updated_at => "2013-09-16 09:19:14" },
  { :wb_target_user_id => 1, :followers_count => 51668480, :statuses_count => 13636, :favourites_count => nil, :followers_per_hour => 171.587, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 08:27:46", :updated_at => "2013-09-18 09:26:46" },
  { :wb_target_user_id => 2, :followers_count => 550554, :statuses_count => 1497, :favourites_count => nil, :followers_per_hour => nil, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 08:27:52", :updated_at => "2013-09-18 08:27:52" },
  { :wb_target_user_id => 3, :followers_count => 10232886, :statuses_count => 16342, :favourites_count => nil, :followers_per_hour => nil, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 08:27:56", :updated_at => "2013-09-18 08:27:56" },
  { :wb_target_user_id => 1, :followers_count => 51668817, :statuses_count => 13637, :favourites_count => nil, :followers_per_hour => 331.566, :followers_per_hour_smoothed => 171.587, :created_at => "2013-09-18 09:28:45", :updated_at => "2013-09-18 09:29:14" },
  { :wb_target_user_id => 2, :followers_count => 550555, :statuses_count => 1498, :favourites_count => nil, :followers_per_hour => 0.984952, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 09:28:47", :updated_at => "2013-09-18 09:29:14" },
  { :wb_target_user_id => 3, :followers_count => 10234570, :statuses_count => 16346, :favourites_count => nil, :followers_per_hour => 1660.02, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 09:28:48", :updated_at => "2013-09-18 09:29:14" },
  { :wb_target_user_id => 4, :followers_count => 535291, :statuses_count => 195, :favourites_count => nil, :followers_per_hour => nil, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 09:28:49", :updated_at => "2013-09-18 09:28:49" },
  { :wb_target_user_id => 1, :followers_count => 51669062, :statuses_count => 13637, :favourites_count => nil, :followers_per_hour => 153.9, :followers_per_hour_smoothed => 187.585, :created_at => "2013-09-18 11:04:16", :updated_at => "2013-09-18 11:04:25" },
  { :wb_target_user_id => 2, :followers_count => 550547, :statuses_count => 1498, :favourites_count => nil, :followers_per_hour => -5.02618, :followers_per_hour_smoothed => 0.984952, :created_at => "2013-09-18 11:04:17", :updated_at => "2013-09-18 11:04:25" },
  { :wb_target_user_id => 3, :followers_count => 10237024, :statuses_count => 16350, :favourites_count => nil, :followers_per_hour => 1541.78, :followers_per_hour_smoothed => 1660.02, :created_at => "2013-09-18 11:04:18", :updated_at => "2013-09-18 11:04:25" },
  { :wb_target_user_id => 4, :followers_count => 535546, :statuses_count => 195, :favourites_count => nil, :followers_per_hour => 160.181, :followers_per_hour_smoothed => nil, :created_at => "2013-09-18 11:04:20", :updated_at => "2013-09-18 11:04:25" },
  { :wb_target_user_id => 1, :followers_count => 51669939, :statuses_count => 13638, :favourites_count => nil, :followers_per_hour => 257.164, :followers_per_hour_smoothed => 184.217, :created_at => "2013-09-18 14:28:53", :updated_at => "2013-09-18 14:29:38" },
  { :wb_target_user_id => 2, :followers_count => 550556, :statuses_count => 1498, :favourites_count => nil, :followers_per_hour => 2.63908, :followers_per_hour_smoothed => 0.383839, :created_at => "2013-09-18 14:28:54", :updated_at => "2013-09-18 14:29:38" },
  { :wb_target_user_id => 3, :followers_count => 10242291, :statuses_count => 16358, :favourites_count => nil, :followers_per_hour => 1544.32, :followers_per_hour_smoothed => 1648.2, :created_at => "2013-09-18 14:28:56", :updated_at => "2013-09-18 14:29:38" },
  { :wb_target_user_id => 4, :followers_count => 535854, :statuses_count => 195, :favourites_count => nil, :followers_per_hour => 90.3079, :followers_per_hour_smoothed => 160.181, :created_at => "2013-09-18 14:28:58", :updated_at => "2013-09-18 14:29:38" },
  { :wb_target_user_id => 1, :followers_count => 51671187, :statuses_count => 13638, :favourites_count => nil, :followers_per_hour => 351.549, :followers_per_hour_smoothed => 191.512, :created_at => "2013-09-18 18:01:53", :updated_at => "2013-09-18 18:02:16" },
  { :wb_target_user_id => 2, :followers_count => 550559, :statuses_count => 1500, :favourites_count => nil, :followers_per_hour => 0.84507, :followers_per_hour_smoothed => 0.609363, :created_at => "2013-09-18 18:01:54", :updated_at => "2013-09-18 18:02:16" },
  { :wb_target_user_id => 3, :followers_count => 10247628, :statuses_count => 16362, :favourites_count => nil, :followers_per_hour => 1503.5, :followers_per_hour_smoothed => 1637.81, :created_at => "2013-09-18 18:01:55", :updated_at => "2013-09-18 18:02:16" },
  { :wb_target_user_id => 4, :followers_count => 536016, :statuses_count => 195, :favourites_count => nil, :followers_per_hour => 45.6374, :followers_per_hour_smoothed => 153.194, :created_at => "2013-09-18 18:01:57", :updated_at => "2013-09-18 18:02:16" },
  { :wb_target_user_id => 1, :followers_count => 51671272, :statuses_count => 13638, :favourites_count => nil, :followers_per_hour => 62.9112, :followers_per_hour_smoothed => 207.516, :created_at => "2013-09-18 19:22:57", :updated_at => "2013-09-18 19:23:42" },
  { :wb_target_user_id => 2, :followers_count => 550558, :statuses_count => 1500, :favourites_count => nil, :followers_per_hour => -0.739979, :followers_per_hour_smoothed => 0.632934, :created_at => "2013-09-18 19:22:59", :updated_at => "2013-09-18 19:23:42" },
  { :wb_target_user_id => 3, :followers_count => 10248917, :statuses_count => 16362, :favourites_count => nil, :followers_per_hour => 954.03, :followers_per_hour_smoothed => 1624.38, :created_at => "2013-09-18 19:22:59", :updated_at => "2013-09-18 19:23:42" },
  { :wb_target_user_id => 4, :followers_count => 536023, :statuses_count => 195, :favourites_count => nil, :followers_per_hour => 5.18199, :followers_per_hour_smoothed => 142.438, :created_at => "2013-09-18 19:23:00", :updated_at => "2013-09-18 19:23:42" },
  { :wb_target_user_id => 5, :followers_count => 2331, :statuses_count => 655, :favourites_count => nil, :followers_per_hour => 0.0, :followers_per_hour_smoothed => 0.0, :created_at => "2013-09-18 19:23:01", :updated_at => "2013-09-18 19:23:01" },
  { :wb_target_user_id => 1, :followers_count => 51673748, :statuses_count => 13640, :favourites_count => nil, :followers_per_hour => 198.353, :followers_per_hour_smoothed => 193.056, :created_at => "2013-09-19 07:51:55", :updated_at => "2013-09-19 07:52:10" },
  { :wb_target_user_id => 2, :followers_count => 550575, :statuses_count => 1502, :favourites_count => nil, :followers_per_hour => 1.36191, :followers_per_hour_smoothed => 0.495643, :created_at => "2013-09-19 07:51:56", :updated_at => "2013-09-19 07:52:10" },
  { :wb_target_user_id => 3, :followers_count => 10263401, :statuses_count => 16383, :favourites_count => nil, :followers_per_hour => 1160.32, :followers_per_hour_smoothed => 1557.34, :created_at => "2013-09-19 07:51:57", :updated_at => "2013-09-19 07:52:10" },
  { :wb_target_user_id => 4, :followers_count => 536345, :statuses_count => 196, :favourites_count => nil, :followers_per_hour => 25.7955, :followers_per_hour_smoothed => 128.712, :created_at => "2013-09-19 07:51:58", :updated_at => "2013-09-19 07:52:10" },
  { :wb_target_user_id => 5, :followers_count => 2332, :statuses_count => 655, :favourites_count => nil, :followers_per_hour => 0.0801086, :followers_per_hour_smoothed => 0.0, :created_at => "2013-09-19 07:52:00", :updated_at => "2013-09-19 07:52:10" },
  { :wb_target_user_id => 1, :followers_count => 51679633, :statuses_count => 13641, :favourites_count => nil, :followers_per_hour => 529.372, :followers_per_hour_smoothed => 193.586, :created_at => "2013-09-19 18:58:56", :updated_at => "2013-09-19 19:01:12" },
  { :wb_target_user_id => 2, :followers_count => 550575, :statuses_count => 1507, :favourites_count => nil, :followers_per_hour => 0.0, :followers_per_hour_smoothed => 0.58227, :created_at => "2013-09-19 18:58:58", :updated_at => "2013-09-19 19:01:12" },
  { :wb_target_user_id => 3, :followers_count => 10276430, :statuses_count => 16401, :favourites_count => nil, :followers_per_hour => 1171.97, :followers_per_hour_smoothed => 1517.64, :created_at => "2013-09-19 18:58:59", :updated_at => "2013-09-19 19:01:12" },
  { :wb_target_user_id => 4, :followers_count => 536301, :statuses_count => 196, :favourites_count => nil, :followers_per_hour => -3.95782, :followers_per_hour_smoothed => 118.42, :created_at => "2013-09-19 18:59:00", :updated_at => "2013-09-19 19:01:12" },
  { :wb_target_user_id => 5, :followers_count => 2332, :statuses_count => 655, :favourites_count => nil, :followers_per_hour => 0.0, :followers_per_hour_smoothed => 0.00801086, :created_at => "2013-09-19 18:59:02", :updated_at => "2013-09-19 19:01:12" },
  { :wb_target_user_id => 1, :followers_count => 51686529, :statuses_count => 13644, :favourites_count => nil, :followers_per_hour => 379.498, :followers_per_hour_smoothed => 227.165, :created_at => "2013-09-20 13:09:13", :updated_at => "2013-09-20 13:15:01" },
  { :wb_target_user_id => 2, :followers_count => 550588, :statuses_count => 1509, :favourites_count => nil, :followers_per_hour => 0.715421, :followers_per_hour_smoothed => 0.524043, :created_at => "2013-09-20 13:09:14", :updated_at => "2013-09-20 13:15:01" },
  { :wb_target_user_id => 3, :followers_count => 10297474, :statuses_count => 16431, :favourites_count => nil, :followers_per_hour => 1158.1, :followers_per_hour_smoothed => 1483.07, :created_at => "2013-09-20 13:09:15", :updated_at => "2013-09-20 13:15:01" },
  { :wb_target_user_id => 4, :followers_count => 536047, :statuses_count => 197, :favourites_count => nil, :followers_per_hour => -13.9782, :followers_per_hour_smoothed => 106.182, :created_at => "2013-09-20 13:09:16", :updated_at => "2013-09-20 13:15:01" },
  { :wb_target_user_id => 5, :followers_count => 2340, :statuses_count => 655, :favourites_count => nil, :followers_per_hour => 0.440259, :followers_per_hour_smoothed => 0.00720977, :created_at => "2013-09-20 13:09:18", :updated_at => "2013-09-20 13:15:01" }
], :without_protection => true )



# WbUser.create([
#   { :wb_id => 1418684827, :name => "CaRro_T", :created_at => "2013-09-18 20:10:27", :updated_at => "2013-09-18 20:10:27" },
#   { :wb_id => 2865743940, :name => "数字营销社区网", :created_at => "2013-09-19 08:07:21", :updated_at => "2013-09-19 08:07:21" }
# ], :without_protection => true )


